### ISSUE TITLE
Migrations? Can't Find Table

### ISSUE THREAD

**Issue by MarcL01** [taskforcedev/laravel-forum#4]
So I installed this package and followed all the instructions but it seems that there are no migrations therefore:

SQLSTATE[42S02]: Base table or view not found: 1146 Table '*******_website.forum_categories' doesn't exist (SQL: select \* from `forum_categories`)

and

SQLSTATE[42S02]: Base table or view not found: 1146 Table '*******_website.forum_categories' doesn't exist

since it can not find the table in the database... Did I miss something or whats wrong with this package?

**Comment by ghost** [comment]
As it currently stands the installation checks (db migrations) happen when you hit the admin routes (I am going to add this into the public routes also further down the line), have you been to /admin/forum? 

The reasoning behind this is to make the install process quicker and easier: 1. install the package, 2. add the service provider, 3. hit the admin route (after all forums are no good without categories and forums).

Please note that there are no releases on this repository so use is still at own risk however I am using it without issues, just need to add a few more things before I release it such as sticky threads, moderator ability to lock threads, etc.

**Comment by ghost** [comment]
I have now updated it so that all routes will check if the migrations are in place (and migrate if not) - I will close this issue for now, feel free to re-open if you still have problems after updating the package.
