### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by aakashrajput** [taskforcedev/laravel-forum#5]
after the instllation ..
when startin it on localhost/fpoke/admin/forums (the forum admin page)
it shows error ErrorException in C:\xampp\htdocs\poke\vendor\taskforcedev\laravel-forum\src\Http\Controllers\BaseController.php line 15: Declaration of Taskforcedev\LaravelForum\Http\Controllers\BaseController::buildData() should be compatible with Taskforcedev\LaravelSupport\Http\Controllers\Controller::buildData($data = Array)

**Comment by ghost** [comment]
Hi,

I have been refactoring the laravel-support package which this package relies on, I have pushed a new version of this package with the laravel-support package locked to the previous laravel-support version.

Please do a composer update and hopefully that should revert the laravel-support package to make this one work.

As an aside, which version of laravel are you using?

**Comment by aakashrajput** [comment]
I am  using laravel 5.3

**Comment by aakashrajput** [comment]
Take  look not working.. 
![screenshot_1](https://cloud.githubusercontent.com/assets/19830621/21519313/1ed07a60-cd12-11e6-96a7-6e8ef78358ce.png)

**Comment by ghost** [comment]
Apologies, I had created the tag but it hadn't pushed before I had replied, it is pushed now, please try again.

**Comment by aakashrajput** [comment]
Np , I can see you worked a lot

**Comment by aakashrajput** [comment]
this time the composer is updated but now getting this error 
![screenshot_2](https://cloud.githubusercontent.com/assets/19830621/21520139/348d0aac-cd18-11e6-81cf-4ee9ad431400.png)

**Comment by ghost** [comment]
What's in require in the composer.json file?

**Comment by aakashrajput** [comment]
"php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "taskforcedev/laravel-support": "1.0.*",
        "taskforcedev/laravel-forum": "dev-master"

**Comment by ghost** [comment]
Ok, yes I am still changing the "5.3 refactoring" in master, I have just pushed a change that should resolve that particular message, I am also setting up a local laravel 5.3 instance to test the package locally.

**Comment by aakashrajput** [comment]
ok, how much time it will take to work ?

**Comment by ghost** [comment]
I think it should be nearly done, if you can keep sending me the errors for now I can fix them re-actively.

**Comment by aakashrajput** [comment]
bro it started now but nothing is there after going to localhost/poke/public/admin/forums 

it just show laravel forum 
![screenshot_3](https://cloud.githubusercontent.com/assets/19830621/21521691/53895fb6-cd25-11e6-9b1d-0fa1782c82d1.png)

**Comment by ghost** [comment]
I have just updated the readme.  The application uses the 'can' method on the user model to determine if you have admin access, per laravel 5.3 convention, you will need to create 1 or more policies to allow administrators to access the admin area (then you can create your forum categories, then create forums within the categories).

**Comment by aakashrajput** [comment]
Btw i want to ask something would you like to join us as a developer we are working on a big project.
starting from jan 10 2017. It is a type of client/server and we need some devs who can work with us 
once we start i hope we can make good money

**Comment by ghost** [comment]
I'd be open to discussing it, feel free to email me with further details.  I do work full time so have to fit other projects around that.

**Comment by ghost** [comment]
The readme is now updated with information on the policies that need to be added, i'm creating them myself to test also.

**Comment by aakashrajput** [comment]
kk
cool
